### ISSUE TITLE
Anatomical region of morphologies

### ISSUE THREAD

**Issue by liesbethvanherpe** [lbologna/bsp_data_repository#12]
Bluepymm needs to know the anatomical region (SP, SO, etc.) of each morphology. The region names should match those used in the recipe. Is it possible to add this information to the metadata files?

**Comment by wvangeit** [comment]
Actually, more precisely, we need to know the region names a certain emodel can be used (can be multiple).

**Comment by romani79** [comment]
We have not inserted any restrictions on which e-model we should use in a given region, in other words each e-model can go in any regions.

**Comment by liesbethvanherpe** [comment]
Thank you, I will use that information to set up the blueypymm input, and allow every e-model in every region.
