### ISSUE TITLE
txt and json files of the cACpyr cells don't match anymore

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#16]
It seems the cAC -> cACpyr transformation created a discrepancy between the json and txt files.
In the json files the e-type is now e.g. cACpyr:
https://github.com/lbologna/bsp_data_repository/blob/master/optimizations/CA1_pyr_cACpyr_dend-050921AM2_axon-051208AM2_20170209104325/CA1_pyr_cACpyr_dend-050921AM2_axon-051208AM2_20170209104325_meta.json

But for that same cell, the txt file still has e-type cAC:
https://github.com/lbologna/bsp_data_repository/blob/master/optimizations/CA1_pyr_cACpyr_dend-050921AM2_axon-051208AM2_20170209104325/CA1_pyr_cACpyr_dend-050921AM2_axon-051208AM2_20170209104325_meta.txt

**Comment by lbologna** [comment]
Fixed it!
Thank you.

Are you using the ..._meta.txt files in your processing? We are now only using the ..._meta.json files, so if it is the same for you we can consider deleting the ..._meta.txt from the optimization folders.

**Comment by wvangeit** [comment]
Sure, no from our side you can delete the txt files.
I got confused when I was manually checking one the cells.

**Comment by lbologna** [comment]
Ok.
Thanks.
