### ISSUE TITLE
Mismatch between MOD mechanism names used in optimization and neurodamus network simulation tool

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#17]
It looks like there is a mismatch between names of the mechanisms used during the optimizations in this repo, and the mod files that are available in our network simulation tool Neurodamus.

For example, the channel 'kdr' is not present in Neurodamus. It looks like at some point hippocampus mod files were added to Neurodamus, but they used specific names, like kdr_hip instead of pure kdr.

Before we can run network simulation (and test our hoc files) this issue needs to be solved

**Comment by lbologna** [comment]
Hi,

Has this issue been solved?
If yes I will close it.

Thanks.

**Comment by wvangeit** [comment]
Not yet. Armando is still in communication with the HPC team about this.

**Comment by wvangeit** [comment]
In the mean time we discovered that there are:
- differences between the mix of MOD files used in different emodels
- clashes between the names of the MOD files between the current files in Neurodamus and Hippocampus
- differences between the exact content of MOD files between different emodels

The first two issues are not too difficult to solve. The last one is more tricky (because the network simulation will obviously use 1 set of MOD files for all the cells).

Armando is going to talk to Michele about how to solve this.
