### ISSUE TITLE
replace_axon hoc code problem

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#21]
This repository doesn't contain the code that defines the protocols, model etc.
On 2017/4/5 you sent us the code you used to run the optimizations (email from Carmen) in a zip file.

However, when we use this code to generate hoc files, the replace_axon function is not correct.
How did you build the HOC files ?

The issue is that in the template.py provided in the zip file, there is a variable called 
hoccode
However, this variable is never used. That's why the bluepyopt hoc code generator uses the default replace_axon instead, and this is not correct.

Also when you fix this, could you change
execute1("create axon[2]\n", CellRef)
into
execute1("create axon[2]", CellRef)
The newline also causes an issue during hoc code generation.

Btw, would it be possible to store this python code somewhere in repo, so that we can pull it from there (instead of having to look for zip files in emails) ?

Thanks

**Comment by clupascu** [comment]
The HOC files are built using analysis.py. In the analysis.py provided in the zip file there is a variable called replace_axon_hoc. After the definition of the above variable, the code used to create the hoc file (in the analyse_cp function) is

opt.evaluator.cell_model.morphology.replace_axon_hoc=replace_axon_hoc
parameter_values = opt.evaluator.param_dict(hof[nrhof])
fitness_protocols = opt.evaluator.fitness_protocols
responses = {}

hoccode =  opt.evaluator.cell_model.create_hoc(param_values=parameter_values)
cp_dir = os.path.dirname(cp_filename)
with open(cp_dir + "/cell"+str(nrhof)+'.hoc', "w") as f:
      f.write(hoccode)

I will fix the newline issue in the template file, even if we are not using the hoccode variable.

I will test once more the code and maybe then we can store the python code somewhere in repo so you can pull it from there.

Thanks

**Comment by wvangeit** [comment]
Ok.
Could you add the replace_axon_hoc to the constructor of the cell model ? (when the evaluator is created). BluePyMM gets the cell model from the evaluator, and at the moment it has the wrong replace_axon_hoc string.
Thanks.

**Comment by clupascu** [comment]
I inserted the code in the repository. For the moment I inserted the code only in one folder CA1_int_bAC_011017HP2_20170510120000/CA1_int_bAC_011017HP2_20170510120000.zip

Please let us know if this would be fine with you.

Moreover, can you please check that now the new replace_axon_hoc string inside the constructor of the cell model generates the same hoc file as in the repository?

Thanks.

**Comment by wvangeit** [comment]
For this to work for us the code needs be correct in all the zip files though

**Comment by clupascu** [comment]
ok. I will insert it in all the zip files.

**Comment by clupascu** [comment]
I inserted the code in all the zip files.

**Comment by wvangeit** [comment]
Ok thanks.
I just opened one of the zip files:
https://github.com/lbologna/bsp_data_repository/blob/master/optimizations/CA1_int_bAC_011017HP2_20170510120000/CA1_int_bAC_011017HP2_20170510120000.zip

It's nice that there is now a template.py in every zip file.

However, it seems the issue in the template.py still persists?
There is still a variable "default_replace_exon_hoc" which is defined but never used.
It's also never passed on to the constructor of the NrnFileMorphologyCustom.

**Comment by clupascu** [comment]
I thought it was as in here: http://bluepyopt.readthedocs.io/en/latest/_modules/bluepyopt/ephys/morphologies.html#NrnFileMorphology

once in template.py from bluepyopt.ephys.morphologies import NrnFileMorphology (row 180)

the init is inherited. And in the init you have

if replace_axon_hoc is None:
    self.replace_axon_hoc = self.**default_replace_axon_hoc**
else:
    self.replace_axon_hoc = replace_axon_hoc

In template.py, in the class NrnFileMorphologyCustom I overwrite the replace_axon function, where the **default_replace_axon_hoc** string is defined. 

Shouldn't be this enough?

Thank you.

**Comment by wvangeit** [comment]
Unfortunately not, it really needs to be given as argument to the constructor.
At the moment you are defining it as a local variable, which is deleted at the end of the function call.
Adding 'self.' to the name of the variable could have helped to prevent deletion.
However, in this case that won't work either, because the 'replace_axon' function is only called during protocol execution (in a separate forked process). We need to get the hoc code for replace axon before that.
So the hoc code needs to be given to the constructor

**Comment by clupascu** [comment]
It is not clear to me then, if all the optimizations were done with the right replace_axon (the same as the one included in the hoc files that are in the repository).

When you say I have to give the hoc code to the constructor of the cell model (when the evaluator is created), do you mean in evaluator.py in create function before 

neuron_cell = model.template.create(etype) ?

Thanks.

**Comment by wvangeit** [comment]
The optimizations only use the python code at the moment, so they should be ok.
You should only not define the variable that defines the hoc code in the python version of replace_axon.
The NrnFileMorphology class has a constructor argument replace_axon_hoc=..., see:
https://github.com/BlueBrain/BluePyOpt/blob/master/bluepyopt/ephys/morphologies.py#L53

In your case, in template.py, there is a line:
return NrnFileMorphologyCustom(...)
there you should add an argument replace_axon_hoc=... that points to the right string with hoc code
(you should also move the default_replace_axon_hoc variable out of replace_axon to be able to access it)

**Comment by clupascu** [comment]
Hi,

I updated the repository with the corrected template.py as you suggested. Let me know if you get the right hoc now.

Thanks.

**Comment by wvangeit** [comment]
Thank you, we will run mm again

**Comment by wvangeit** [comment]
It seems this problem is still present. @romani79 has built a circuit using this git hash of this repo:
9877ddf0e16583748a4b5dc179146ef273e59b3f

The circuit simulation using Neurodamus fails because of wrong hoc code in the replace_axon.

E.g. the model CA1_int_cAC_011017HP2_20171010141433 still doesn't seem to have the hoccode variable (with the correct content in the model/template.py, but that variable is used nowhere.

The same problem also seems to exist in the latest master of the repo.

@clupascu Can you fix this ? Then we can regenerate the HOC files.

**Comment by clupascu** [comment]
I will take a look at the code again and try to fix this.

**Comment by clupascu** [comment]
The latest master of the repo is updated. Can you try to regenerate the HOC files again? 
Thanks.

**Comment by wvangeit** [comment]
Ok, it looks like this issue is solved in the latest HOC files that were generated
