### ISSUE TITLE
Print statement in replace axon creates large amount of output

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#22]
Could you remove the statement: 
print "Target stub axon length:", L_target, "um, equivalent length: ", L_real "um"
from the replace axon function in the hoc code.

The team running the network simulations mentioned that this generates one line of output for every cell (i.e. 800k lines :-) )

**Comment by clupascu** [comment]
I removed the print statement from the replace axon function in the hoc code.

**Comment by wvangeit** [comment]
Thanks
