### ISSUE TITLE
Extracting the e-model from CA1_int_cAC_011017HP2_20171010141433

### ISSUE THREAD

**Issue by liesbethvanherpe** [lbologna/bsp_data_repository#23]
In the folder 'checkpoints' of CA1_int_cAC_011017HP2_20171010141433, I found three .hoc files and three .pkl files. This is different from the previous release of e-models, where there was only one file of each type. Could you provide a script that extracts the best model from these files?

**Comment by liesbethvanherpe** [comment]
The same goes for folder CA1_int_cAC_990611HP2_20170927115554, where I found two files of each type.

**Comment by lbologna** [comment]
Hello,

yes we could provide a script for extracting the best model.

Would it be preferable to have a batch script that extracts (and stores)
the best individual from each optimization of the entire repository or
would you prefer a simpler script to be run on an individual optimization
folder?


On Mon, Nov 13, 2017 at 4:22 PM, Liesbeth Vanherpe <notifications@github.com

**Comment by liesbethvanherpe** [comment]
Hi Luca,

A simple script that works on each individual optimization folder will do fine for the moment. Thanks!

**Comment by genric** [comment]
Hi Luca,
    Could you also introduce back the cell.hoc file which loads the model. Currently BlueNaaS is broken: it cannot load the model because it doesn't know which file to select. Thanks.

**Comment by lbologna** [comment]
Hi Liesbeth, Genrich,

we plan to do this:

1) introduce a field in the "...meta.json" file, named "best" which
indicates the best individual
2) reintroduce the "cell.hoc" in the "checkpoints" folder. In case multiple
.hoc are generated (and already present) in the "checkpoints" folder (e.g.
"cell_seed2_0.hoc", "cell_seed3_0.hoc", ...), a "cell.hoc" file will be
added (to the same folder) which will be a copy of the .hoc referring to
the best individual.

Are both points fine with you?

Cheers.

**Comment by genric** [comment]
Yep, sounds good to me. Thanks.

**Comment by wvangeit** [comment]
One small suggestion. Couldn't you point from inside the json file to the correct hoc file name, and let Genrich use that field ? (Unless if that's too complex for Genrich in his code)
It's just me, but I hate the 'cp' command ;-)

**Comment by liesbethvanherpe** [comment]
All the above sound good to me.

**Comment by genric** [comment]
As long as there is some convention on what is a 'single' single cell model in this directory structure I am good with that. I can load it from some meta file or load directly the hoc file. Thanks.

**Comment by lbologna** [comment]
Hello,

We propose to add this two fields to the ___meta.json:

"best run": "seed3.pkl",
"best cell": "cell_seed3_0.hoc", 

which specify the name of the files contained in the "checkpoints" folder and referring to the best optimization run and the corresponding best model (respectively).

If this information is complete for you, more specifically if it serves your purposes regardless of the number of .pkl and .hoc files present in the "checkpoints" folder, we proceed with the changes.

**Comment by liesbethvanherpe** [comment]
Yes, thank you, "best_run" and "best_cell" work for me.

**Comment by genric** [comment]
Me too. Thanks.

**Comment by rmiglior** [comment]
Ok. We will add the two fields: 

"best_run": "seed3.pkl",
"best_cell": "cell_seed3_0.hoc",

Thanks.

**Comment by rmiglior** [comment]
Hello.
We created a new release of the repo (v2.0.1) with the new fields (i.e. "best_run" and "best_cell") in the metadata files as agreed.

Please, let us know if this works for you.
Thanks.

**Comment by liesbethvanherpe** [comment]
Tested and approved!
