### ISSUE TITLE
Key CA1_PC_cACnoljp vs CA1_PC_cAC_sig in "CA1_pyr_cACpyr_dend-050921AM2_axon-051208AM2_20170915145830"

### ISSUE THREAD

**Issue by liesbethvanherpe** [lbologna/bsp_data_repository#25]
The metadata file of CA1_pyr_cACpyr_dend-050921AM2_axon-051208AM2_20170915145830 contains a key value pair "fitting_name": "CA1_PC_cACnoljp". This is not consistent with the content of the config/ folder, where the key "CA1_PC_cAC_sig" is used in the .json files .

Could this be fixed? Thanks.

**Comment by liesbethvanherpe** [comment]
The same is true for CA1_pyr_cACpyr_dend-990803_axon-051208AM2_20170909151002.

**Comment by liesbethvanherpe** [comment]
Is it possible that this is the case for all the pyramidal cells?

**Comment by rmiglior** [comment]
yes, probably this is the case. I will fix this quickly. thanks

**Comment by rmiglior** [comment]
Done. Please let me know if everything is ok. thanks

**Comment by liesbethvanherpe** [comment]
This works now - thank you!
