### ISSUE TITLE
Two morphologies for model CA1_int_cAC_980513B_20180119155952

### ISSUE THREAD

**Issue by alex4200** [lbologna/bsp_data_repository#26]
The model CA1_int_cAC_980513B_20180119155952 seems to have two morphologies in its morphology folder from here:

https://github.com/lbologna/bsp_data_repository/raw/master/optimizations/CA1_int_cAC_980513B_20180119155952/CA1_int_cAC_980513B_20180119155952.zip

- 970509HP2.asc  
- 980513B.asc

Is there a mistake for that model?

**Comment by lbologna** [comment]
This has been fixed. Could you please check again? Thanks

**Comment by lbologna** [comment]
Checked and closed.
