### ISSUE TITLE
Missing hoc file for best model in CA1_int_cAC_010710HP2_20180118155959

### ISSUE THREAD

**Issue by genric** [lbologna/bsp_data_repository#27]
Hi,
    We just noticed that BlueNaaS fails to load this model: CA1_int_cAC_010710HP2_20180118155959. It is because the best_cell property in json is pointing to the hoc file which is not packaged in the zip. This is the value it has: "best_cell": "cell_seed7_0.hoc". Could you please add that file to the zip or change the value of best_cell to something that is packaged in the zip archive. Thank you.

**Comment by rmiglior** [comment]
Done. I have updated CA1_int_cAC_010710HP2_20180118155959_meta.json
