### ISSUE TITLE
Provide link to MOD file repo in json file describing emodels

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#29]
It would be good to have some link from the emodels to the git repo containing the MOD files.
Probably the best place for this is the json file in every zip file in this repo.

It should contain enough info for a tool to automatically fetch the MOD files. 
So at least the URL of the repo, and the release / commit of the files used.

We should make sure that inside one emodel release, the same MOD release is used for all emodels.
(Or if this is not the case due to time constraints, we have to make sure the different MOD release are compatible, because the network simulator can only use 1 set of MOD files)

**Comment by rmiglior** [comment]
Ok. We can add a new key in the meta.json pointing to the correct .mod release version.
Say: "mod_set":"https://github.com/cnr-ibf-pa/hbp-bsp-models/tree/v1.0.0"

Would that be good for  you?

Just to make sure (so as not to be obliged to update all the meta every time): 

1) the simulator will need to fetch all the mod for a single model, from a single place/single link (i.e. a versioned .mod git repo)
2) different network models may use different link from where to fetch the set, provided that point 1) is satisfied

Is that correct?

Thanks

**Comment by wvangeit** [comment]
I would propose something like:
mod_repo: https://github.com/cnr-ibf-pa/hbp-bsp-models.git
mod_tag: v1.0.0
mod_path: mod_files

(with mod_path the path inside the repo)

That way a tool can automatically fetch the MOD files using:
git clone --branch v1.0.0 https://github.com/cnr-ibf-pa/hbp-bsp-models.git
cd hbp_bsp_models/mod_files

Regarding 1)
Yes, I would not, for reproducibility, update the mod git repo/tag link for all the emodels every time the mod repo changes. When a single cell modeling tool (e.g. BlueNaas) runs the emodel it should ideally use the original MOD files used for the optimization.

Regarding 2)
This is a difficult question since it's difficult to automate. The network sim can only use 1 MOD release. So the question will be which one to use. What probably should happen is that we use the 'latest' MOD release used by any emodel in a network simulation. So we have to make sure new MOD releases don't change the behavior of older emodels (or otherwise we do need to reoptimize). This is something we could check automatically in a travis plan I guess.
It also means that the MOD release shouldn't fork, because otherwise the 'latest' release is basically undefined.

**Comment by clupascu** [comment]
So, to do a network sim each emodel's mod_tag should point to the same value or not?

**Comment by wvangeit** [comment]
Ideally yes (but do not manually change the mod_tag in the json of an emodel to point to a MOD release that was not used for the optimization ...), but I do understand that optimizations are expensive, and that we don't want to reoptimize all cells when something small to the input changes. 
So we can allow different tags in the same network sim (and we take the 'latest' tag to run the simulation). We only need to make sure that for all the emodels the results don't change when using the tag used in the network, compared to the tag used for the optimization (if they are different we should reoptimize).

**Comment by rmiglior** [comment]
Hi!
as we agreed I added the new keys in the meta.json
"channels": "kdrb, na3, kmb, kap, hd, can, cal, cat, kdb, cagk, cacum, kca",
"mod_repo": "https://github.com/cnr-ibf-pa/hbp-bsp-models.git",
"mod_tag": "v1.0.0",

Thanks :)

**Comment by rmiglior** [comment]
sorry the new keys are

"mod_repo": "https://github.com/cnr-ibf-pa/hbp-bsp-models.git",
"mod_tag": "v1.0.0",
"mod_path": "mod_files",

**Comment by wvangeit** [comment]
Ok, looks good, thx
