### ISSUE TITLE
Morphology files with the same name but different content

### ISSUE THREAD

**Issue by genric** [lbologna/bsp_data_repository#30]
Hi,
    These two have different content but same name:
CA1_int_cNAC_990111HP2_20180118155424/morphology/990111HP2.asc
CA1_int_cAC_980120A_20180115155814/morphology/990111HP2.asc
    Should different morphologies be named differently? Thanks.

**Comment by genric** [comment]
Found more of these:
CA1_int_cNAC_011017HP2_20180119154507/morphology/011017HP2.asc
CA1_int_cAC_011017HP2_20180121160005/morphology/011017HP2.asc

CA1_int_cNAC_011023HP2_20180118154613/morphology/011023HP2.asc
CA1_int_bAC_011023HP2_20180116154023/morphology/011023HP2.asc

CA1_int_cNAC_970627BHP1_20180120154830/morphology/970627BHP1.asc
CA1_int_cAC_970627BHP1_20180120160112/morphology/970627BHP1.asc

CA1_int_cAC_980513B_20180119155952/morphology/980513B.asc
CA1_int_cNAC_980513B_20180119155127/morphology/980513B.asc

CA1_int_cNAC_990611HP2_20180120155246/morphology/990611HP2.asc
CA1_int_cAC_990611HP2_20180122160209/morphology/990611HP2.asc

**Comment by clupascu** [comment]
Different e-types were optimized using the same morphology. That is why for different optimizations you find the same morphology.

**Comment by clupascu** [comment]
This content CA1_int_cAC_980120A_20180115155814/morphology/990111HP2.asc doesn't exist anymore. It was fixed yesterday #28.

**Comment by genric** [comment]
Correct, that one(in CA1_int_cAC_980120A_20180115155814) is gone now.
With the others problem is that the morphologies defined inside those files, having the same file name, are different. So they probably diverged and are from different morphology releases. It is not a big deal and I'll try to register them as a separate entities in nexus but it will be a bit confusing to understand why morphologies coming from the same release have same names. We have discussed it with @wvangeit and @romani79, so we'll try to come up with some suggestions on how to improve the model release process considering future nexus integration. Thanks, we can close this for now.
