### ISSUE TITLE
replace_axon needs to be fixed

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#36]
The replace axon has the following lines commented out:
```
//                access axon[0]
//                i1 = v(0.0001) // used when serializing sections prior to sim start

//                access axon[1]
//                i2 = v(0.0001) // used when serializing sections prior to sim start
```
This creates problems when running the simulation with Neurodamus (axo-axonal projecting cells crash). 
Can you reenable these lines in the zip files ? (it shouldnt affect the optimisations).

Not sure where this problem originated. It could have been in the original replace_axon we provided to you, or did you disable these line ?

Thx

**Comment by clupascu** [comment]
I disabled these lines as some of the PC morphologies, having only one axonal section, were not running in the Hippocampus Validation UseCase. With the 2 lines enabled,the old output hoc template was expecting 2 axonal sections.

**Comment by clupascu** [comment]
Are the morphologies with only one axonal section creating problems to you?

**Comment by wvangeit** [comment]
We'll need these lines because they assign section ids to the axonal sections, which are very important for the synaptic connections.
We probably should adapt that hoc code to allow for axons with < 2 sections (and with the i* lines active).

@romani79 do you know if there are morphologies left in the circuit that might have axons with < 2 sections ? Or is there a process that might filter these out ?

**Comment by romani79** [comment]
> @romani79 do you know if there are morphologies left in the circuit that might have axons with < 2 sections ? Or is there a process that might filter these out ?

The morphs with very short axons can exists only in the morphology repository, then I use mix'n'match to substitute the short axon with a correspondent long one.

**Comment by wvangeit** [comment]
we fixed the hoc code for the replace axon now. @clupascu, could you in the optimizations also fix this by replacing the 4 lines you commented out by:
```
                access axon[0]                                                                                                                                                                          
                i1 = v(0.0001) // used when serializing sections prior to sim start                                                                                                                     
                                                                                                                                                                                                        
                if( nSec > 1 ) {                                                                                                                                                                                        
                    access axon[1]                                                                                                                                                                          
                    i2 = v(0.0001) // used when serializing sections prior to sim start                                                                                                                     
                } else {                                                                                                                                                                                                                                                                                                                                                              
                    i2 = i1                                                                                                                                                                                              
                }                                                                                                                                                                                                                            
```
Thanks.

**Comment by rmiglior** [comment]
Hi Werner
I replaced the 4 lines as you suggested. Ciao
Rosanna

**Comment by clupascu** [comment]
@wvangeit Once this is done, does it still make sense to check in the Travis plan if the hoc template can be loaded properly? What neuron tests do you suggest that we should still do in the Travis plan (issue #31)?

**Comment by wvangeit** [comment]
@rmiglior Will close the issue
