### ISSUE TITLE
Small fix for replace_axon

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#37]
We found a small issue in the replace_axon code you're using. Fixing it shouldn't change results, but might be slightly faster.

In the template.py there is a replace_axon method defined of NrnFileMorphologyCustom. 
In it there is the code
```
for seg in section:
                #seg.x, seg.diam
                diams.append(seg.diam)
                lens.append(L / nseg)
                if count == nseg_total:
                    break
```
This code should incremented the 'count' variable. So it should be something like
```
for seg in section:
                #seg.x, seg.diam
                diams.append(seg.diam)
                lens.append(L / nseg)
                count += 1
                if count == nseg_total:
                    break
```

**Comment by rmiglior** [comment]
Hi Werner
we fixed this point. The new release is the v3.1.11.

**Comment by wvangeit** [comment]
Thx
