### ISSUE TITLE
Mismatch between number of features and number of feature values

### ISSUE THREAD

**Issue by liesbethvanherpe** [lbologna/bsp_data_repository#7]
There appears to be a mismatch between the number of features in config/features.json (60) and the number of feature values in checkpoints/seed5.pkl (63) for cell CA1_pyr_cAC_dend-050921AM2_axon-051208AM2_20170209104325 .

**Comment by lbologna** [comment]
Hi,
Thanks for your comment.
We will have a look and eventually fix this after the 19th April.

Regards

**Comment by liesbethvanherpe** [comment]
Did you find time to look at this particular cell?

**Comment by lbologna** [comment]
Hi,

We checked our data but we were unfortunately not able to retrace the mismatch.
We are going to delete this optimization folder.

Regards.

**Comment by liesbethvanherpe** [comment]
Would it be possible to remove the above-mentioned folder from the repository?

**Comment by lbologna** [comment]
Hi,

It's done!
Thank you.

Kind regards.
