### ISSUE TITLE
Optimized morphologies should exist in morphology release

### ISSUE THREAD

**Issue by wvangeit** [lbologna/bsp_data_repository#8]
One of the requirements of BluePyMM is that the cell names used for the optimization also exist in the morphology release used to build the circuit.

This is e.g. not the case for some morphologies in this repo.

In the neocortex this requirement is necessary to compare the scores of an unrepaired to a repaired morphology.
Since the hippocampus pipeline doesn't repair morphologies, we might drop this requirement for BluePyMM.

Two options:
- we change bluepymm to drop this requirement
- other morphologies are used for the optimization

**Comment by lbologna** [comment]
Hi Werner,

After discussion with Michele and Armando, for the moment, we opted for the first option you propose:

- we change bluepymm to drop this requirement

Regards

**Comment by wvangeit** [comment]
The requirement was dropped in bluepymm
